config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do  
  root 'application#landing'
  resource :launch, only: :create
  get '/config' => 'launches#xml_config'
  constraints(->(request) { request.host != 'qqq.firstdraft.com' }) do
    get '/teacher' => 'resources#teacher_backdoor'
    get '/student' => 'resources#student_backdoor'
  end
  resources :attached_images
  resources :images
  resources :question_tags
  resources :tags
  resources :required_fields
  resources :question_templates
  resources :responses
  resources :upvotes
  resources :questions
  resources :users, only: %i[]
  resources :submissions, only: %i[]
  resources :contexts, only: %i[show edit]
  resources :resources, only: %i[show edit]
  resources :enrollments, only: %i[]
  resources :consumptions, only: %i[]
  resources :tool_consumers, only: %i[]
  resources :credentials, only: %i[]
  devise_for :administrators
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/upvote.rb
# == Schema Information
#
# Table name: upvotes
#
#  id            :bigint           not null, primary key
#  post_type     :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  enrollment_id :integer
#  post_id       :integer
#

class Upvote < ApplicationRecord
  belongs_to :enrollment
  belongs_to :post, polymorphic: true
  # belongs_to :question
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :set_upvote, only: [:show, :edit, :update, :destroy]

  # GET /upvotes
  def index
    @upvotes = Upvote.all
  end

  # GET /upvotes/1
  def show
  end

  # GET /upvotes/new
  def new
    @upvote = Upvote.new
  end

  # GET /upvotes/1/edit
  def edit
  end

  # POST /upvotes
  def create
    @upvote = Upvote.new(upvote_params)

    if @upvote.save
      redirect_to @upvote.post, notice: 'Upvote was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /upvotes/1
  def update
    if @upvote.update(upvote_params)
      redirect_to @upvote, notice: 'Upvote was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /upvotes/1
  def destroy
    @upvote.destroy
    redirect_to @upvote.post, notice: 'Upvote was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upvote
      @upvote = Upvote.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def upvote_params
      params.require(:upvote).permit(:post_id, :post_type, :enrollment_id)
    end
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/upvotes/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Upvote #<%= upvote.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Question</dt>
      <dd><%= upvote.question_id %></dd>

      <dt>Enrollment</dt>
      <dd><%= upvote.enrollment_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back upvote, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_upvote_url(upvote), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to upvote, method: :delete, data: { confirm: "Do you really want to delete this upvote?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(upvote.updated_at) %> ago
  </div>
</div>

app/views/upvotes/_form.html.erb
<% was_validated = upvote.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(upvote, html: form_html_options) do |f| %>
  <div class="form-group">
    <% question_id_class = "form-control" %>
    <% question_id_was_invalid = upvote.errors.include?(:question_id) %>

    <% if was_validated %>
      <% if question_id_was_invalid %>
        <% question_id_class << " is-invalid" %>
      <% else %>
        <% question_id_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :question_id %>

    <%= f.number_field :question_id, class: question_id_class, placeholder: "Enter question" %>
    <% if question_id_was_invalid %>
      <% upvote.errors.full_messages_for(:question_id).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% enrollment_id_class = "form-control" %>
    <% enrollment_id_was_invalid = upvote.errors.include?(:enrollment_id) %>

    <% if was_validated %>
      <% if enrollment_id_was_invalid %>
        <% enrollment_id_class << " is-invalid" %>
      <% else %>
        <% enrollment_id_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :enrollment_id %>

    <%= f.number_field :enrollment_id, class: enrollment_id_class, placeholder: "Enter enrollment" %>
    <% if enrollment_id_was_invalid %>
      <% upvote.errors.full_messages_for(:enrollment_id).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/upvotes/_list_item.html.erb
<%= link_to upvote, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Upvote #<%= upvote.id %>

    <small class="text-muted">
      <%= time_ago_in_words(upvote.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/upvotes/_table_row.html.erb
<tr>
  <td>
    <%= upvote.question_id %>
  </td>

  <td>
    <%= upvote.enrollment_id %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to upvote, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_upvote_url(upvote), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to upvote, method: :delete, data: { confirm: "Do you really want to delete this upvote?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/upvotes/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Upvote #<%= @upvote.id %>
      </h2>

      <div class="card-body">
        <%= render "form", upvote: @upvote %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/upvotes/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Upvotes

      <%= link_to new_upvote_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Question
            </th>

            <th>
              Enrollment
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @upvotes, partial: "table_row", as: :upvote %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @upvotes.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :upvote %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Upvotes

        <%= link_to new_upvote_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @upvotes, partial: "list_item", as: :upvote %>
      </div>
    </div>
  </div>
</div>

app/views/upvotes/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Upvote
      </h2>

      <div class="card-body">
        <%= render "form", upvote: @upvote %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/upvotes/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @upvote, partial: "card", as: :upvote %>
  </div>
</div>