config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do  
  root 'application#landing'
  resource :launch, only: :create
  get '/config' => 'launches#xml_config'
  constraints(->(request) { request.host != 'qqq.firstdraft.com' }) do
    get '/teacher' => 'resources#teacher_backdoor'
    get '/student' => 'resources#student_backdoor'
  end
  resources :attached_images
  resources :images
  resources :question_tags
  resources :tags
  resources :required_fields
  resources :question_templates
  resources :responses
  resources :upvotes
  resources :questions
  resources :users, only: %i[]
  resources :submissions, only: %i[]
  resources :contexts, only: %i[show edit]
  resources :resources, only: %i[show edit]
  resources :enrollments, only: %i[]
  resources :consumptions, only: %i[]
  resources :tool_consumers, only: %i[]
  resources :credentials, only: %i[]
  devise_for :administrators
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  context_id :integer
#

class Tag < ApplicationRecord
  belongs_to :context
  has_many :question_tags, :dependent => :destroy

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name, :context_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Tag #<%= tag.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= tag.name %></dd>

      <dt>Context</dt>
      <dd><%= tag.context_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back tag, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_tag_url(tag), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to tag, method: :delete, data: { confirm: "Do you really want to delete this tag?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(tag.updated_at) %> ago
  </div>
</div>

app/views/tags/_form.html.erb
<% was_validated = tag.errors.any? %>

<% form_html_options = { novalidate: true, class: "mb-3" } %>

<%= form_for(tag, html: form_html_options) do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = tag.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>

    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% tag.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="form-group">
    <% context_id_class = "form-control" %>
    <% context_id_was_invalid = tag.errors.include?(:context_id) %>

    <% if was_validated %>
      <% if context_id_was_invalid %>
        <% context_id_class << " is-invalid" %>
      <% else %>
        <% context_id_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :context_id %>

    <%= f.number_field :context_id, class: context_id_class, placeholder: "Enter context" %>
    <% if context_id_was_invalid %>
      <% tag.errors.full_messages_for(:context_id).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/tags/_list_item.html.erb
<%= link_to tag, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    Tag #<%= tag.id %>

    <small class="text-muted">
      <%= time_ago_in_words(tag.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/tags/_table_row.html.erb
<tr>
  <td>
    <%= tag.name %>
  </td>

  <td>
    <%= tag.context_id %>
  </td>

  <td>
    <div class="btn-group">
      <%= link_to tag, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-search-plus fa-fw"></i>
      <% end %>

      <%= link_to edit_tag_url(tag), class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-edit fa-fw"></i>
      <% end %>

      <%= link_to tag, method: :delete, data: { confirm: "Do you really want to delete this tag?" }, class: "btn btn-sm btn-outline-secondary" do %>
        <i class="fas fa-trash-alt fa-fw"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/tags/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Tag #<%= @tag.id %>
      </h2>

      <div class="card-body">
        <%= render "form", tag: @tag %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tags/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Tags

      <%= link_to new_tag_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Table example -->

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>
              Name
            </th>

            <th>
              Context
            </th>

            <th>
              Actions
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render collection: @tags, partial: "table_row", as: :tag %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Card deck example -->

<% @tags.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :tag %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Tags

        <%= link_to new_tag_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @tags, partial: "list_item", as: :tag %>
      </div>
    </div>
  </div>
</div>

app/views/tags/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Tag
      </h2>

      <div class="card-body">
        <%= render "form", tag: @tag %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @tag, partial: "card", as: :tag %>
  </div>
</div>